<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>

<?php require 'templates/layout/header.phtml' ?>
<?php foreach ($cap as $cap): ?>
    <div class="container text-box-g rounded-4 p-3 mt-2 mb-2 col-12 col-sm-10 col-md-8 col-lg-6 mx-auto">
        <p class="h1 p-2 d-flex justify-content-center">Temporada <?php echo $cap->temporada ?></p>
        <p class="h3 p-2 d-flex justify-content-center"><?php echo $cap->titulo ?></p>
        <p class="p-4"><?php echo $cap->descripcion ?></p>
        <div class="d-flex justify-content-center col-12 mt-4">
            <iframe width="100%" height="360" src="<?php echo $cap->video ?>"
                frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
        </div>
    </div>
<?php endforeach ?>
<?php require 'templates/layout/footer.phtml' ?>