<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>

<?php require 'templates/layout/header.phtml' ?>
<?php foreach ($char as $char): ?>
    <div class="container text-box-g rounded-4 p-3 mt-3 mb-3">
        <div class="d-flex flex-column flex-md-row justify-content-between align-items-center">
            <p class="h1 p-2 text-center flex-grow-1"><?php echo $char->nombre ?></p>
            <img src="<?php echo $char->imagen; ?>" alt="<?php echo $char->nombre; ?>" class="rounded-4 img-fluid" style="max-width:300px; max-height:300px;">
        </div>
        <p class="p-4"><?php echo $char->descripcion ?></p>
    </div>
<?php endforeach ?>
<?php require 'templates/layout/footer.phtml' ?>