<?php require_once 'templates/layout/header.phtml' ?>
<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<form method='post' action="addseason">
    <div class="text-box-g m-2 p-3 rounded">
        <div class='form-group m-2'>
            <label for='nombre'>Nombre</label>
            <input type='nombre' class='form-control' id='nombre' name='nombre' placeholder="Ingrese el nombre de la temporada" required>
        </div>
        <button type='submit' class='btn btn-primary m-2'>Añadir</button>
    </div>
</form>
<?php require_once 'templates/layout/footer.phtml' ?>