<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>

<?php require_once 'templates/layout/header.phtml' ?>
<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<form method='post' action="addseason">
    <div class="text-box-g m-2 p-3 rounded">
        <div class='form-group m-2'>
            <label for='nombre'>Nombre</label>
            <input type='nombre' class='form-control' id='nombre' name='nombre' placeholder="Ingrese el nombre de la temporada" required>
        </div>
        <button type='submit' class='btn btn-primary m-2'>Añadir</button>
    </div>
</form>
<?php require_once 'templates/layout/footer.phtml' ?>