<?php require_once 'templates/layout/header.phtml'?>
<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<?php foreach ($cap as $cap):?>
<form method='post' action="editcap/<?php echo  $cap->id ?>">
    <div class='form-group'>
        <label for='titulo'>Titulo</label>
        <input type='titulo' class='form-control' id='titulo' name='titulo' placeholder="Titulo del capitulo" value="<?php echo $cap->titulo?>" required>
    </div>
    <div class='form-group'>
        <label for='descripcion'>Descripción</label>
        <input type='descripcion' class='form-control' id='descripcion' name='descripcion' placeholder="Descripcion del capitulo" value="<?php echo $cap->descripcion?>" required>
    </div>
    <div class='form-group'>
        <label for='video'>Video</label>
        <input type='video' class='form-control' id='video' name='video' placeholder="Url de video" value="<?php echo $cap->video?>" required>
    </div>
    
    <div class='form-group'>
        <label for='video'>Temporada</label>
        <select name="temporada" id="[]">
            <?php foreach ($temps as $temp): ?>
            <option value="<?php echo $temp->id_temporada?>"><?php echo $temp->nombre?></option>
            <?php endforeach ?>
        </select>
    </div>
    <button type='submit' class='btn btn-primary'>Editar</button>
</form>
<?php endforeach?>
<?php require_once 'templates/layout/footer.phtml'?>