<?php require_once 'templates/layout/header.phtml'?>
<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<form method='post' action="addcap">
    <div class='form-group'>
        <label for='titulo'>Titulo</label>
        <input type='titulo' class='form-control' id='titulo' name='titulo' placeholder="Ingrese el titulo del capitulo" required>
    </div>
    <div class='form-group'>
        <label for='descripcion'>Descripción</label>
        <input type='descripcion' class='form-control' id='descripcion' name='descripcion' placeholder="Ingrese la descripcion del capitulo" required>
    </div>
    <div class='form-group'>
        <label for='video'>Video</label>
        <input type='video' class='form-control' id='video' name='video' placeholder="Ingrese la url de video" required>
    </div>
    <div class='form-group'>
        <label for='video'>Temporada</label>
        <select name="temporada" id="[]">
            <?php foreach ($temps as $temp): ?>
            <option value="<?php echo $temp->id_temporada?>"><?php echo $temp->nombre?></option>
            <?php endforeach ?>
        </select>
    </div>
    <button type='submit' class='btn btn-primary'>Añadir</button>
</form>
<?php require_once 'templates/layout/footer.phtml'?>