<?php require_once 'templates/layout/header.phtml' ?>
<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<form method='post' action="addcap">
    <div class="text-box-g m-2 p-3 rounded">
        <div class='form-group m-2'>
            <label for='titulo'>Titulo</label>
            <input type='titulo' class='form-control' id='titulo' name='titulo' placeholder="Ingrese el titulo del capitulo" required>
        </div>
        <div class='form-group m-2'>
            <label for='descripcion'>Descripción</label>
            <input type='descripcion' class='form-control' id='descripcion' name='descripcion' placeholder="Ingrese la descripcion del capitulo" required>
        </div>
        <div class='form-group m-2'>
            <label for='video'>Video</label>
            <input type='video' class='form-control' id='video' name='video' placeholder="Ingrese la url de video" required>
        </div>
        <div class='form-group m-2'>
            <select name="temporada" id="temporada" class="btn btn-primary form-select w-25 text-start">
                <?php foreach ($temps as $temp): ?>
                    <option value="<?php echo $temp->id_temporada ?>"><?php echo $temp->nombre ?></option>
                <?php endforeach ?>
            </select>
        </div>
        <button type='submit' class='btn btn-danger m-2'>Añadir</button>
    </div>
</form>
<?php require_once 'templates/layout/footer.phtml' ?>