<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>

<?php require 'templates/layout/header.phtml' ?>

<body>
    <main class="d-flex align-items-center justify-content-start h-100 p-3">
        <div class="rounded-4 p-4 ms-0 me-0 izq-der col-md-8 col-12 mt-5">
            <img src="assets/logoslugterra.png" alt="Logo de Bajoterra" class="img-fluid mb-3">
            <div class="rounded-4 p-4 text-box-g">
                <h4>Bajoterra es una aventura épica de comedia de ciencia ficción ambientada en el subterráneo, donde la munición está viva y sólo los rápidos sobreviven! En este mundo subterráneo luminoso, de alta tecnología, cada caverna tiene una nueva aventura, una nueva batalla y pequeñas babosas extrañas que descubrir.</h4>
            </div>
        </div>
    </main>

    <?php require 'templates/layout/footer.phtml' ?>
</body>

</html>