<?php require 'templates/layout/header.phtml' ?>
<div class="dropdown m-2">
    <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown"
        aria-expanded="false">
        Temporadas
    </button>
    <?php if ($this->user): ?>
        <button class="btn btn-dark m-1" onclick="addCaps()">Añadir capitulo</button>
    <?php endif ?>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="caps">Todas las Temporadas</a></li>
        <?php foreach ($temps as $temp): ?>
            <li><a class="dropdown-item" href="caps/temp/<?php echo $temp->id_temporada ?>"><?php echo $temp->nombre ?></a></li>
        <?php endforeach ?>
    </ul>
</div>
<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<ul class="scrollable-list text-box-g rounded-2 p-3 d-flex flex-wrap">
    <?php foreach ($caps as $cap): ?>
        <li class="list-item item-task rounded-2 p-3 m-1 d-grid gap-1 col-12 col-sm-6 col-md-4 col-lg-3">
            <div class="d-flex flex-column">
                <a href="cap/<?php echo $cap->id ?>">
                    <b class="h4 fw-bold d-grid gap-1"><?php echo $cap->nombre ?></b>
                    <b class="fw-light"><?php echo $cap->titulo ?></b>
                </a>
                <?php if ($this->user): ?>
                    <div class="d-flex flex-row d-grid gap-1">
                        <button type="button" class="btn btn-primary m-1" onclick="editCaps()">Editar</button>
                        <button type="button" class="btn btn-danger m-1" onclick="deleteCaps(<?php echo $cap->id ?>)">Eliminar</button>
                    </div>
                <?php endif ?>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<script src="js/main.js"></script>

<?php require 'templates/layout/footer.phtml' ?>