<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>

<?php require 'templates/layout/header.phtml' ?>
<?php if ($this->user): ?>
    <button class="btn btn-dark m-1" onclick="addTemp()">Añadir temporada</button>
<?php endif ?>
<ul class="text-box-g rounded-2 p-3">
    <?php foreach ($temps as $temp): ?>
        <li class="list-item item-task rounded-2 p-3 m-1 d-grid gap-1">
            <a href="caps/temp/<?php echo $temp->id_temporada ?>"><b><?php echo $temp->nombre ?></b></a>
            <div class="d-flex">
                <?php if ($this->user): ?>
                    <button class="btn btn-primary m-1" onclick="editTemp(<?php echo $temp->id_temporada ?>)">Editar</button>
                    <button class="btn btn-danger m-1" onclick="deleteTemp(<?php echo $temp->id_temporada ?>)">Eliminar</button>
                <?php endif ?>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<script src="js/main.js"></script>

<?php require 'templates/layout/footer.phtml' ?>