<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>

<?php require 'templates/layout/header.phtml' ?>
<div class="dropdown m-2">
    <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown"
        aria-expanded="false">
        Temporadas
    </button>
    <a href="add/caps">Añadir capitulo</a>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="caps">Todas las Temporadas</a></li>
        <?php foreach ($temps as $temp): ?>
            <li><a class="dropdown-item" href="caps/temp/<?php echo $temp->id_temporada ?>"><?php echo $temp->nombre ?></a></li>
        <?php endforeach ?>
    </ul>
</div>
<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<ul class="text-box-g rounded-2 p-3">
    <?php foreach ($caps as $cap): ?>
        <a href="cap/<?php echo $cap->id ?>">
            <li class="list-item item-task rounded-2 p-3 m-1 d-grid gap-1">
                <b class="fw-bold">Temporada: <?php echo $cap->nombre ?></b>
                <b class="fw-light"><?php echo $cap->titulo ?></b>
                <?php if ($this->user): ?>
                    <a href="#">Editar</a> <!-- agregar confirmacion para los 2 -->
                    <a href="delete/caps/<?php echo $cap->id ?>">Eliminar</a> <!-- deberia ser un boton esto, no un hipervinculo feo -->
                <?php endif ?>
            </li>
        </a>
    <?php endforeach ?>
</ul>

<script src="js/main.js"></script>

<?php require 'templates/layout/footer.phtml' ?>