<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>

<?php require 'templates/layout/header.phtml' ?>
<?php if ($this->user): ?>
    <a href="#">Añadir temporada</a>
<?php endif ?>
<ul class="text-box-g rounded-2 p-3">
    <?php foreach ($temps as $temp): ?>
        <li class="list-item item-task rounded-2 p-3 m-1 d-grid gap-1">
            <a href="caps/temp/<?php echo $temp->id ?>"><b><?php echo $temp->nombre ?></b></a>
            <?php if ($this->user): ?>
                <a href="edit/season/<?php echo $temp->id ?>">Editar</a> <!-- agregar confirmacion para los 2 -->
                <a href="delete/season/<?php echo $temp->id ?>">Eliminar</a> <!-- deberia ser un boton esto, no un hipervinculo feo -->
            <?php endif ?>
        </li>
    <?php endforeach ?>
</ul>
<?php require 'templates/layout/footer.phtml' ?>