<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>

<?php require 'templates/layout/header.phtml' ?>
<?php if ($this->user): ?>
    <button class="btn btn-dark m-1" onclick="addCharact()">Añadir personaje</button>
<?php endif ?>
<ul class="text-box-g rounded-2 p-3 d-flex flex-wrap justify-content-center">
    <?php foreach ($chars as $char): ?>
        <li class="list-item item-task rounded-2 p-3 m-2 d-flex flex-column col-12 col-sm-6 col-md-4 col-lg-3">
            <div class="d-flex flex-column align-items-center">
                <a href="char/<?php echo $char->id ?>" class="text-center">
                    <img src="<?php echo $char->imagen; ?>" alt="<?php echo $char->nombre; ?>" class="img-fluid rounded-circle" style="max-width:100px; max-height:100px;">
                    <b class="h3 fw-bold d-grid gap-1 mt-2"><?php echo $char->nombre ?></b>
                    <b class="fw-light"><?php echo $char->descripcion ?></b>
                </a>
                <div class="d-flex flex-row d-grid gap-1 mt-2">
                    <?php if ($this->user): ?>
                        <button class="btn btn-primary m-1" onclick="editChar(<?php echo $char->id ?>)">Editar</button>
                        <button type="button" class="btn btn-danger m-1" onclick="deleteChar(<?php echo $char->id ?>)">Eliminar</button>
                    <?php endif ?>
                </div>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<script src="js/main.js"></script>

<?php require 'templates/layout/footer.phtml' ?>