<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>

<?php require 'templates/layout/header.phtml' ?>
<button class="btn btn-dark m-1" onclick="agregarPersonaje()">Añadir personaje</button>
<ul class="text-box-g rounded-2 p-3">
    <?php foreach ($chars as $char): ?>
        <li class="list-item item-task rounded-2 p-3 d-flex align-items-center">
            <a href="char/<?php echo $char->id ?>">
                <div class="d-flex align-content-center">
                    <div class="d-flex flex-column col-11 m-1">
                        <b class="h3 fw-bold d-grid gap-1"><?php echo $char->nombre ?></b>
                        <b class="fw-light"><?php echo $char->descripcion ?></b>
                        <div class="d-flex flex-row d-grid gap-1">
                            <?php if ($this->user): ?>
                                <a href="edit/chars/<?php echo $char->id ?>"><button class="btn btn-primary m-1" href="#">Editar</button></a>
                                <button type="button" class="btn btn-danger m-1" onclick="eliminarChar(<?php echo $char->id ?>)">Eliminar</button>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="img-fluid col-1 m-1 rounded-2">
                        <img src="<?php echo $char->imagen; ?>" alt="<?php echo $char->nombre; ?>" style="max-width:100px; max-height:100px;">
                    </div>
                </div>

            </a>
        </li>
    <?php endforeach ?>
</ul>

<script src="js/main.js"></script>

<?php require 'templates/layout/footer.phtml' ?>