<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>

<?php require 'templates/layout/login-header.phtml' ?>

<div class="d-flex justify-content-center">
    <form method='post' action='login' class="text-center w-50">
        <div class="row justify-content-center">
            <div class="col-md-6 text-box-g m-2 p-3 rounded w-50">
                <div class='form-group m-2'>
                    <label for='name'>Usuario</label>
                    <input type='name' class='form-control' id='name' name='name' placeholder="Ingrese su usuario" required>
                </div>
                <div class='form-group m-2'>
                    <label for='password'>Contraseña</label>
                    <input type='password' class='form-control' id='password' name='password' placeholder="Ingrese su contraseña" required>
                </div>
                <div class="d-flex flex-column align-items-center">
                    <button type='submit' class='btn btn-primary m-2'>Iniciar Sesion</button>
                </div>
            </div>
        </div>
    </form>

    <?php if ($error): ?>
        <div class='alert alert-danger w-50 m-2' role='alert'>
            <?= $error ?>
        </div>
    <?php endif ?>
</div>

<?php require 'templates/layout/footer.phtml' ?>