<?php require 'templates/layout/login-header.phtml' ?>

<div class="d-flex justify-content-center flex-column">
    <form method='post' action='login'>
        <div class="text-box-g m-2 p-3 rounded w-50">
            <div class='form-group m-2'>
                <label for='name'>Usuario</label>
                <input type='name' class='form-control' id='name' name='name' placeholder="Ingrese su usuario" required>
            </div>
            <div class='form-group m-2'>
                <label for='password'>Contraseña</label>
                <input type='password' class='form-control' id='password' name='password' placeholder="Ingrese su contraseña" required>
            </div>
            <div class="d-flex flex-row align-items-center">
                <button type='submit' class='btn btn-primary m-2'>Iniciar Sesion</button>
                <span>¿No tienes usuario? <a class="btn btn-danger m-2" href="register"><label>Registrate</label></a></span>
            </div>
        </div>
    </form>

    <?php if ($error): ?>
        <div class='alert alert-danger w-50 m-2' role='alert'>
            <?= $error ?>
        </div>
    <?php endif ?>
</div>
<?php require 'templates/layout/footer.phtml' ?>