<?php require 'templates/layout/login-header.phtml'?>
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingresa tu email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Contraseña</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Ingresa tu contraseña">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Ingrese nuevamente la contraseña</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Ingresa tu contraseña">
  </div>
  <button type="submit" class="btn btn-primary">Registrarse</button>
</form>
<?php require 'templates/layout/footer.phtml'?>