<?php require 'templates/layout/login-header.phtml' ?>

<div class="d-flex justify-content-center">
  <form method='post' action='register' class="text-center w-30"> <!-- Ajusta el ancho aquí -->
    <div class="text-box-g m-2 p-3 rounded">
      <div class='form-group m-2'>
        <label for='exampleInputEmail1'>Email</label>
        <input type='email' class='form-control' id='exampleInputEmail1' aria-describedby='emailHelp' placeholder="Ingresa tu email" required>
      </div>
      <div class='form-group m-2'>
        <label for='exampleInputPassword1'>Contraseña</label>
        <input type='password' class='form-control' id='exampleInputPassword1' placeholder="Ingresa tu contraseña" required>
      </div>
      <div class='form-group m-2'>
        <label for='exampleInputPassword2'>Ingrese nuevamente la contraseña</label>
        <input type='password' class='form-control' id='exampleInputPassword2' placeholder="Ingresa tu contraseña" required>
      </div>
      <div class="d-flex flex-column align-items-center">
        <button type='submit' class='btn btn-primary m-2'>Registrarse</button>
        <span class="mt-2">¿Ya tienes usuario? <a class="btn btn-danger m-2" href="login"><label>Iniciar Sesion</label></a></span>
      </div>
    </div>
  </form>

  <?php if ($error): ?>
    <div class='alert alert-danger w-30 m-2' role='alert'> <!-- Ajusta el ancho aquí -->
      <?= $error ?>
    </div>
  <?php endif ?>
</div>

<?php require 'templates/layout/footer.phtml' ?>