<?php require 'templates/layout/login-header.phtml' ?>
<form>
  <div class="text-box-g m-2 p-3 rounded w-50">
    <div class="form-group m-2">
      <label for="exampleInputEmail1">Email</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingresa tu email">
    </div>
    <div class="form-group m-2">
      <label for="exampleInputPassword1">Contraseña</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Ingresa tu contraseña">
    </div>
    <div class="form-group m-2">
      <label for="exampleInputPassword1">Ingrese nuevamente la contraseña</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Ingresa tu contraseña">
    </div>
    <div class="d-flex flex-row align-items-center">
      <button type='submit' class='btn btn-primary m-2'>Registrarse</button>
      <span>¿Ya tienes usuario? <a class="btn btn-danger m-2" href="login"><label>Iniciar Sesion</label></a></span>
    </div>
  </div>
</form>
<?php require 'templates/layout/footer.phtml' ?>