<!DOCTYPE html>
<html lang="en">

<!-- head -->

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Bajoterra</title>
</head>

<body>
    <!-- main header -->
    <header class="header">
        <nav class="navbar navbar-expand-lg p-auto justify-content-between align-items-center">
            <a class="navbar-brand fw-bold" href="home"><img class="img-fluid" src="assets/logoslugterra.png"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="caps">Capitulos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="seasons">Temporadas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="chars">Personajes</a>
                    </li>
                    <?php if (!$this->user): ?>
                        <li class="nav-item">
                            <a class="nav-link" href="showLogin">Iniciar sesion</a>
                        </li>
                    <?php endif ?>
                    <?php if ($this->user): ?>
                        <li class="nav-item">
                            <a class="nav-link" href="logout">Cerrar sesion</a>
                        </li>
                    <?php endif ?>
            </div>
        </nav>
    </header>

    <main class="container mt-3">