<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Bajoterra</title>
</head>

<body>
    <!-- main header -->
    <header class="header">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="home"><img class="img-fluid" src="assets/logoslugterra.png" alt="Logo"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="caps">Capitulos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="seasons">Temporadas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="chars">Personajes</a>
                    </li>
                    <?php if (!$this->user): ?>
                        <li class="nav-item">
                            <a class="nav-link" href="showLogin">Iniciar sesión</a>
                        </li>
                    <?php endif ?>
                    <?php if ($this->user): ?>
                        <li class="nav-item">
                            <a class="nav-link" href="logout">Cerrar sesión</a>
                        </li>
                    <?php endif ?>
                </ul>
            </div>
        </nav>
    </header>

    <main class="container mt-3">

</body>

</html>